services:
  dashboard:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=file:./data/aircraft.db
      - ULTRAFEEDER_HOST=http://192.168.1.50:8080
      - POLL_INTERVAL=30000
      - DATA_RETENTION_DAYS=30
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - collector

  collector:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=file:./data/aircraft.db
      - ULTRAFEEDER_HOST=http://192.168.1.50:8080
      - POLL_INTERVAL=30000
      - DATA_RETENTION_DAYS=30
      - NODE_ENV=production
    restart: unless-stopped
    command: npm run collector

volumes:
  data:
    driver: local 